#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP3201-baseline_client

EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/protocol_examples_common/
EXTRA_COMPONENT_DIRS +=  ../../components/esp_iowa/

include $(IDF_PATH)/make/project.mk
